# Generated by Django 5.2 on 2025-05-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0002_alter_person_options_alter_book_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
