# Generated by Django 5.2 on 2025-05-07 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0003_borrow_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id_reservation',
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 5, 23)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 5, 10)),
        ),
    ]
