# Generated by Django 5.2 on 2025-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0004_remove_reservation_id_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_year_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
