# Generated by Django 5.2 on 2025-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0005_book_publication_year_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_year_int',
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=0),
        ),
    ]
