# Generated by Django 5.2 on 2025-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0006_remove_book_publication_year_int_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=0),
        ),
    ]
