# Generated by Django 5.2 on 2025-05-09 17:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0008_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('children', 'Children'), ('Young Adult', 'Ya'), ('Adult', 'Adult'), ('All', 'All')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='event_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, default='', null=True, upload_to='event_posters/'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 5, 24)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Book Reading', 'Book Reading'), ('Workshop', 'Workshop'), ('Author Visit', 'Author Visit'), ('Exhibition', 'Exhibition'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_Id', models.CharField(max_length=70, unique=True)),
                ('type_payment', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default='', max_length=20)),
                ('amount', models.FloatField(default=0.0)),
                ('card_info', models.CharField(default='', max_length=150)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theApp.borrow')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
