# Generated by Django 5.2 on 2025-05-09 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0009_remove_event_image_event_audience_event_event_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_reservations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
