# Generated by Django 5.2 on 2025-05-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0011_alter_borrow_due_date_alter_event_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='person',
        ),
    ]
