# Generated by Django 5.2 on 2025-05-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0013_alert_title_book_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unread_alerts',
            field=models.IntegerField(default=0),
        ),
    ]
